# Generated by Django 5.0 on 2026-06-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_analytics_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Еда'), ('transport', 'Транспорт'), ('business', 'Бизнес'), ('health', 'Здоровье'), ('education', 'Образование'), ('entertainment', 'Развлечения'), ('shopping', 'Покупки'), ('utilities', 'Коммунальные'), ('credit', 'Кредит'), ('other', 'Другое')], default='other', max_length=50),
        ),
    ]
